name:     memoizer
synopsis: An alternative to representable functors.
version:  0.0.1
category: Data
author:   Aliaksei Valatouski

library:
  source-dirs: src
  exposed-modules:
    - Control.Comonad.Memoized.Store
    - Data.Memoizer
  dependencies:
    - adjunctions
    - array
    - base
    - comonad
    - containers
    - hashable
    - unordered-containers
    - vector
